package com.oracle.xmlns.sca_bloqueologinusuario.frameworkseguridad.frameworkmediator;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.2.4
 * 2018-12-20T13:35:46.016-05:00
 * Generated source version: 3.2.4
 *
 */
@WebService(targetNamespace = "http://xmlns.oracle.com/SCA_BloqueoLoginUsuario/FrameworkSeguridad/FrameworkMediator", name = "Framework_ptt")
@XmlSeeAlso({com.bolivariano.frameworkseguridadtypes.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface FrameworkPtt {

    @WebMethod(action = "http://xmlns.oracle.com/SCA_BloqueoLoginUsuario/FrameworkSeguridad/FrameworkMediator/loginAplicacion")
    @WebResult(name = "LoginAplicacion_out", targetNamespace = "http://www.bolivariano.com/FrameworkSeguridadTypes", partName = "reply")
    public com.bolivariano.frameworkseguridadtypes.LoginAplicacionOut loginAplicacion(
        @WebParam(partName = "blrequest", name = "LoginAplicacion_in", targetNamespace = "http://www.bolivariano.com/FrameworkSeguridadTypes")
        com.bolivariano.frameworkseguridadtypes.LoginAplicacionIn blrequest
    );
}
