package com.oracle.xmlns.sca_bloqueologinusuario.frameworkseguridad.frameworkmediator;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.4
 * 2018-11-27T14:58:30.290-05:00
 * Generated source version: 3.2.4
 *
 */
@WebServiceClient(name = "FrameworkMediator_ep",
                  wsdlLocation = "file:/D:/Proyectos/CASH-MANAGEMENT/DOCUMENTOS_CASH/Fuentes/Offline/jsf-spring/src/main/resources/wsframework/FrameworkSeguridadSinSeg_1.wsdl",
                  targetNamespace = "http://xmlns.oracle.com/SCA_BloqueoLoginUsuario/FrameworkSeguridad/FrameworkMediator")
public class FrameworkMediatorEp extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://xmlns.oracle.com/SCA_BloqueoLoginUsuario/FrameworkSeguridad/FrameworkMediator", "FrameworkMediator_ep");
    public final static QName FrameworkPt = new QName("http://xmlns.oracle.com/SCA_BloqueoLoginUsuario/FrameworkSeguridad/FrameworkMediator", "Framework_pt");
    static {
        URL url = null;
        try {
            url = new URL("file:/D:/Proyectos/CASH-MANAGEMENT/DOCUMENTOS_CASH/Fuentes/Offline/jsf-spring/src/main/resources/wsframework/FrameworkSeguridadSinSeg_1.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(FrameworkMediatorEp.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:/D:/Proyectos/CASH-MANAGEMENT/DOCUMENTOS_CASH/Fuentes/Offline/jsf-spring/src/main/resources/wsframework/FrameworkSeguridadSinSeg_1.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public FrameworkMediatorEp(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public FrameworkMediatorEp(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public FrameworkMediatorEp() {
        super(WSDL_LOCATION, SERVICE);
    }

    public FrameworkMediatorEp(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public FrameworkMediatorEp(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public FrameworkMediatorEp(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns FrameworkPtt
     */
    @WebEndpoint(name = "Framework_pt")
    public FrameworkPtt getFrameworkPt() {
        return super.getPort(FrameworkPt, FrameworkPtt.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns FrameworkPtt
     */
    @WebEndpoint(name = "Framework_pt")
    public FrameworkPtt getFrameworkPt(WebServiceFeature... features) {
        return super.getPort(FrameworkPt, FrameworkPtt.class, features);
    }

}
